name: HapticsTestApp
options:
  bundleIdPrefix: com.yourname
  deploymentTarget: "15.0"
  createIntermediateGroups: true
  groupSortPosition: top
  generateEmptyDirectories: true

targets:
  HapticsTestApp:
    type: application
    platform: iOS
    sources:
      - path: HapticsTestApp
        excludes:
          - "*.DS_Store"
    resources:
      - path: HapticsTestApp/Assets.xcassets
      - path: HapticsTestApp/Base.lproj
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourname.HapticsTestApp
        INFOPLIST_FILE: HapticsTestApp/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        TARGETED_DEVICE_FAMILY: "1,2"
        IPHONEOS_DEPLOYMENT_TARGET: "15.0"
        SWIFT_VERSION: "5.0"
        CODE_SIGN_STYLE: Automatic
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: false
