name: HapticsTestApp
options:
  bundleIdPrefix: com.yourname
  deploymentTarget: "15.0"
  groupSortPosition: top
targets:
  HapticsTestApp:
    type: application
    platform: iOS
    sources:
      - HapticsTestApp
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.yourname.HapticsTestApp
      INFOPLIST_FILE: HapticsTestApp/Info.plist
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      TARGETED_DEVICE_FAMILY: 1,2
      IPHONEOS_DEPLOYMENT_TARGET: 15.0
      SWIFT_VERSION: 5.0
      CODE_SIGN_STYLE: Automatic
